# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: CVE&reg; Program
contact: https://cveform.mitre.org/
description: > # this means to ignore newlines until "baseurl:"
The mission of the CVE&reg; Program is to identify, define, and catalog publicly 
disclosed cybersecurity vulnerabilities. There is one CVE Record for each 
vulnerability in the catalog. The vulnerabilities are discovered then assigned 
and published by organizations from around the world that have partnered with 
the CVE Program. Partners publish CVE Records to communicate consistent 
descriptions of vulnerabilities. Information technology and cybersecurity 
professionals use CVE Records to ensure they are discussing the same issue, 
and to coordinate their efforts to prioritize and address the vulnerabilities.
baseurl: "" # the subpath of your site, e.g. /blog

# Build settings
markdown: kramdown
